name:  Chise
services:
  Chise:
    context: .
    dockerfile: Dockerfile.Chise
    env_file: .env.ani

  CL:
    build:  
      context: .
      dockerfile: Dockerfile.CL
    env_file:  .env.aeon

  Sina:
    build:  
      context: .
      dockerfile: Dockerfile.Sina
    env_file:  .env.ae
